### ISSUE TITLE
Title bar throw an exception when init it.

### ISSUE THREAD

**Issue by TerryCheni** [lepoco/wpfui#1292]
### Describe the bug

I have add a title bar in mian window, and when inti it. it throw a NullReferenceException as flow:

` Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Wpf.Ui.Controls.TitleBar.HwndSourceHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)`

And if I remove this contorl, window is empty, no exception throw

### To Reproduce

Init application.

### Expected behavior

Do not throw this exception.

### OS version

Windows 10 22H2
19045.5131

### .NET version

.Net 6 

### WPF-UI NuGet version

3.0.5
4.0.0-rc.3

**Comment by TerryCheni** [comment]
Sorry, I forgot add
``` xaml
<ResourceDictionary>
      <ResourceDictionary.MergedDictionaries>
        <ui:ThemesDictionary Theme="Dark" />
        <ui:ControlsDictionary />
      </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
```
into app.xaml
