### ISSUE TITLE
Navigation: Support to MVVM

### ISSUE THREAD

**Issue by ClaudioGalgani** [lepoco/wpfui#46]
Using MVVM pattern, the NavigationItem Type could be a page with an assigned DataContext, the viewmodel. 
The NavigationToElement uses the Activator.CreateInstance(element.Type) creating the object and I haven't found a clean way to assign it the DataContext. 

My solution currently is to modify the NavigateToElement assigning the DataContext.

private void NavigateToElement(INavigationItem element, bool refresh)
{
  [...]

  element.Instance = Activator.CreateInstance(element.Type);

  var control = element as FrameworkElement;
  var controlInstance = element.Instance as FrameworkElement;

  if (controlInstance.DataContext == null)
    controlInstance.DataContext = control.DataContext;

  [...]
}

Alternative could be to find a way to pass parameters to the NavigationItem, to use in an Activator.CreateInstance with parameters.

**Comment by kfrancis** [comment]
If you want to see an example where Nav isn't working in an MVVM scenario, I've got this https://github.com/kfrancis/abp-wpf.

In my example, the Window/Pages have a single constructor that takes the ViewModel as the single dependency (and sets DataContext) but I'm getting:

```
System.MissingMethodException: Constructor on type 'Acme.BookStore.Wpf.Views.BookIndex' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceInternal(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName)
   at WPFUI.Controls.Navigation.CreateInstance(Type pageType)
   at WPFUI.Controls.Navigation.NavigateToElement(INavigationItem element, Boolean refresh, Object dataContext)
   at WPFUI.Controls.Navigation.Navigate(Int32 pageIndex, Boolean refresh, Object dataContext)
   at WPFUI.Controls.Navigation.Navigate(String pageTag, Boolean refresh, Object dataContext)
   at WPFUI.Controls.Navigation.Item_OnClicked(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by ClaudioGalgani** [comment]
Hi Francis, 

Thanks for interest.
Before to go through your example, I'd like to share my current implementation.
I saw that in the newer version the Navigate method accept an optional datacontext.
The Demo navigates through the tag string not passing the datacontext so it is null.
To retrieve the DataContext associated to the selected page, at the Navigate  methods I've added the datacontext if present.
In this way the datacontext/viewmodel follow the page/view respecting the pattern.

Here the code:

`public bool Navigate(int pageIndex, bool refresh = false, object dataContext = null)
{
    if (Items == null || Items?.Count == 0 || Frame == null || pageIndex < 0)
        return false;

    var indexShift = pageIndex;

    for (var i = 0; i < Items.Count; i++)
    {
        if (i != indexShift || !Items[i].IsValid) continue;

        PreviousPageIndex = SelectedPageIndex;
        SelectedPageIndex = i;

        //Assign the dataContext
        dataContext ??= (Items[i] as FrameworkElement)?.DataContext;

        NavigateToElement(Items[i], refresh, dataContext);

        return true;
    }

    indexShift -= Items.Count;

    if (Footer == null || !Footer.Any() || indexShift < 0)
        return false;

    for (var i = 0; i < Footer.Count; i++)
    {
        if (i != indexShift || !Footer[i].IsValid) continue;

        PreviousPageIndex = SelectedPageIndex;
        SelectedPageIndex = i;

        //Assign the dataContext 
        dataContext ??= (Footer[i] as FrameworkElement)?.DataContext;

        NavigateToElement(Footer[i], refresh, dataContext);

        return true;
    }

    return false;
}`

**Comment by kfrancis** [comment]
I'm not sure where that would take place. There doesn't appear to be an event of the same name.

**Comment by kfrancis** [comment]
https://github.com/kfrancis/abp-wpf/blob/main/src/Acme.BookStore.Wpf/Views/MainWindow.xaml.cs#L40
